### ISSUE TITLE
Getting the updateindex! mechanism into SparseArrays.jl

### ISSUE THREAD

**Issue by MaximilianJHuber** [WIAS-PDELib/ExtendableSparse.jl#2]
`updateindex!`s way of updating entries of a SparseMatrixCSC really should go into `SparseArrays.jl`, but after a quick search I have not seen any issue or pull-request with that intention.

**Comment by j-fu** [comment]
Hi,  I had this in mind. Didn't want to make too much trouble though... Thanks for testing!

**Comment by j-fu** [comment]
Submitted   [#35428](https://github.com/JuliaLang/julia/issues/35428).
