### ISSUE TITLE
Adding zero-valued elements

### ISSUE THREAD

**Issue by MaximilianJHuber** [WIAS-PDELib/ExtendableSparse.jl#4]
```
using SparseArrays
C = spzeros(2,2)
C[1,1] = 0.0
```
[does not add](https://github.com/JuliaLang/julia/blob/b1ceadc524e507f466e00681df6e8bca652dba53/stdlib/SparseArrays/src/sparsematrix.jl#L2497) an entry to the sparse matrix. Neither should:
```
using ExtendableSparse
A = ExtendableSparseMatrix(2, 2)
A[1,1] = 0.0
```
but it does.

**Comment by j-fu** [comment]
Hi, thanks for the hint. The idea behind this is that it in principle should be possible to have entries which are zero "by chance" . The way I use it  I  so far check before if I don't want zeros there.

I agree that this behavior may feel unexpected. Indeed it is probably better to be consistent with  SparseMatrixCSC. 

The case I have in mind may be handled by another API call. I try to find time to modify this.

**Comment by j-fu** [comment]
Ok thanks for the suggestion, I implemented this.
