### ISSUE TITLE
In-place preconditioner solves

### ISSUE THREAD

**Issue by Anemometer** [WIAS-PDELib/ExtendableSparse.jl#6]
Interfacing with [`IterativeSolvers.jl`](https://github.com/JuliaMath/IterativeSolvers.jl) requires custom preconditioner types to support an in-place left division `ldiv!(p::JacobiPreconditioner, x::SubArray)`.
For instance, the following code produces an error:
```julia
using LinearAlgebra, SparseArrays, IterativeSolvers, ExtendableSparse
A = sprand(10,10,.5) + 1.0I
x = ones(size(A,2))
b = A*x
jacprec = JacobiPreconditioner(A)
y = gmres(A,b;Pl=jacprec)

ERROR: MethodError: no method matching ldiv!(::JacobiPreconditioner{Float64,Int64}, ::SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}) [...]
```
caused by [l. 232](https://github.com/JuliaMath/IterativeSolvers.jl/blob/f9f8c83bc0ca34b753dd971de395ef7b36726d69/src/gmres.jl#L232) of `IterativeSolvers.jl`.
At least for the `JacobiPreconditioner` this is easily fixable.

**Comment by j-fu** [comment]
I see, thank you!
Can you make  a PR ?
